"""add_profile_photo_verification_fields

Revision ID: b602f97bfbbb
Revises: 741ce2a387c3
Create Date: 2026-08-17 00:13:16.486301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b602f97bfbbb'
down_revision: Union[str, None] = '741ce2a387c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('profile_picture_url', sa.String(length=500), nullable=True))
    op.add_column('companies', sa.Column('profile_completeness', sa.Integer(), nullable=True))
    op.add_column('job_seeker_profiles', sa.Column('profile_picture_url', sa.String(length=500), nullable=True))
    op.add_column('job_seeker_profiles', sa.Column('profile_completeness', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified_at')
    op.drop_column('job_seeker_profiles', 'profile_completeness')
    op.drop_column('job_seeker_profiles', 'profile_picture_url')
    op.drop_column('companies', 'profile_completeness')
    op.drop_column('companies', 'profile_picture_url')
    # ### end Alembic commands ###
